Repository higlass/higlass, pull requests merged in 2018-11, with the labels that each got.

#362 Flekschas/fix update build
  .npmignore
  CHANGELOG.md
  app/index.html
  app/styles/page.css
  karma.conf.js
  package.json
  webpack.config.js
Labels: bug, critical

#372 Re-add example
  docs/examples/1d-annotations.html
Labels: enhancement

#398 Base-10 log on heatmap mouseover
  app/scripts/HeatmapTiledPixiTrack.js
Labels: bug

#415 Replaced PUT with PATCH cmd; added tileset management commands
  docs/higlass_server.rst
Labels: enhancement

#414 Restore working index.html
  app/index.html
Labels: bug

#375 Flekschas/add interaction handling to 1d annotations
  app/scripts/Annotations1dTrack.js
  app/scripts/Annotations2dTrack.js
  app/scripts/Chromosome2DAnnotations.js
  app/scripts/HiGlassComponent.js
  app/scripts/api.js
  app/scripts/configs/index.js
  app/scripts/utils/index.js
  app/scripts/utils/some.js
  app/scripts/utils/test-helpers.js
  docs/examples/1d-annotations.html
  docs/higlass_developer.rst
  package.json
  test/APITests.js
  test/view-configs.js
Labels: feature

#423 Fix duplicated wheel forwarding
  app/scripts/HiGlassComponent.js
  app/scripts/TrackRenderer.js
  app/scripts/utils/clone-event.js
  app/scripts/utils/forward-event.js
Labels: bug, critical

#430 Expose version
  app/scripts/api.js
  test/APITests.js
  test/view-configs.js
Labels: enhancement

#436 It's b to the randification time!
  app/scripts/HiGlassComponent.js
  app/scripts/services/element-resize-listener.js
  app/scripts/services/index.js
  app/scripts/utils/get-element-dim.js
  app/scripts/utils/get-xylofon.js
  app/scripts/utils/index.js
  scripts/sass-optimizer.js
  webpack.config.js
Labels: enhancement
