Repository higlass/higlass, pull requests merged in 2019-06, with the labels that each got.

#664 Flekschas/pixijs v5
  CHANGELOG.md
  app/index.html
  app/scripts/HeatmapTiledPixiTrack.js
  app/scripts/HiGlassComponent.js
  docs/examples/apis/axis-margin.html
  docs/examples/apis/cursor-location.html
  docs/examples/apis/default-track-options.html
  docs/examples/apis/get-min-max-value.html
  docs/examples/apis/load-annotations/index.html
  docs/examples/apis/mouse-move-zoom.html
  docs/examples/apis/reset-viewport.html
  docs/examples/apis/set-track-value-scale-limits.html
  docs/examples/apis/svg.html
  docs/examples/apis/trackViewer.html
  docs/examples/apis/zoom-to.html
  docs/examples/others/adjust-view-spacing.html
  docs/examples/others/global-mouse-position.html
  docs/examples/others/test_drag.html
  docs/javascript_api.rst
  karma.conf.js
  package-lock.json
  package.json
  test/BarTrackTests.js
Labels: enhancement

#662 Flekschas/awesome lazy share view as link modal
  CHANGELOG.md
  app/scripts/ExportLinkDialog.js
  app/scripts/HiGlassComponent.js
  app/styles/ExportLinkDialog.module.scss
Labels: bug, enhancement

#666 Flekschas/fix mousemove performance
  CHANGELOG.md
  app/scripts/HiGlassComponent.js
  app/scripts/TrackRenderer.js
Labels: bug

#691 Fix protocol to avoid CORS errors
  CHANGELOG.md
  app/scripts/OSMTilesTrack.js
Labels: bug

#689 Pkerpedjiev/sync value scale bug
  CHANGELOG.md
  app/scripts/HiGlassComponent.js
Labels: bug

#698 Flekschas/flexibilify mapbox
  CHANGELOG.md
  app/scripts/MapboxTilesTrack.js
  app/scripts/TrackRenderer.js
  app/scripts/configs/tracks-info.js
  docs/examples/examples.html
  docs/examples/others/mapbox.html
Labels: enhancement

#695 Flekschas/rgba colormaps
  CHANGELOG.md
  app/scripts/utils/color-domain-to-rgba-array.js
Labels: enhancement

#696 Flekschas/osm hotfix
  CHANGELOG.md
  app/scripts/OSMTilesTrack.js
Labels: bug

#706 Flekschas/fix minor issue with the positioning of track-related divs
  CHANGELOG.md
  app/scripts/TiledPlot.js
Labels: bug

#694 Flekschas/throttle debounce tile fetching
  CHANGELOG.md
  app/scripts/TiledPixiTrack.js
  app/scripts/services/tile-proxy.js
  app/scripts/utils/index.js
  app/scripts/utils/throttle-and-debounce.js
Labels: enhancement

#687 Flekschas/upper right lower left heatmap
  CHANGELOG.md
  app/scripts/HeatmapTiledPixiTrack.js
  app/scripts/HiGlassComponent.js
  app/scripts/PixiTrack.js
  app/scripts/TiledPixiTrack.js
  app/scripts/configs/options-info.js
  app/scripts/configs/tracks-info.js
  app/scripts/services/tile-proxy.js
  app/scripts/worker.js
  docs/examples/examples.html
  docs/examples/viewconfs/diagonal-split-heatmap.json
  docs/track_types.rst
  test/HeatmapTests.js
Labels: feature
