Repository higlass/higlass, pull requests merged in 2019-01, with the labels that each got.

#526 Flekschas/expose mix library to plugins
  CHANGELOG.md
  app/scripts/configs/available-for-plugins.js
Labels: easy, enhancement

#528 Flekschas/bigwig enhanced summary
  CHANGELOG.md
  app/scripts/HorizontalLine1DPixiTrack.js
  app/scripts/TiledPlot.js
  app/scripts/configs/options-info.js
  app/scripts/configs/tracks-info.js
  docs/examples/examples.html
  docs/examples/viewconfs/bigwig-aggregation-modes.json
Labels: enhancement

#524 Flekschas/overlay tracks 1d and 2d
  app/scripts/OverlayTrack.js
  app/scripts/TiledPlot.js
  docs/examples/viewconfs/overlay-tracks.json
  test/OverlayTrackTests.js
  test/view-configs/overlay-annotations-1d-2d.js
Labels: easy, enhancement

#529 Implement option for constant horizontal indicators
  CHANGELOG.md
  app/scripts/HorizontalTiled1DPixiTrack.js
  docs/examples/examples.html
  docs/examples/viewconfs/1d-constant-indicators.json
  docs/track_types.rst
  test/Horizontal1DTrackTests.js
  test/view-configs/horizontal-1d-line-track-with-const.js
Labels: feature

#525 Flekschas/overlay chrom grid
  app/index.html
  app/scripts/Chromosome2DGrid.js
  app/scripts/ChromosomeGrid.js
  app/scripts/HiGlassComponent.js
  app/scripts/TiledPlot.js
  app/scripts/TrackRenderer.js
  app/scripts/configs/tracks-info.js
  docs/examples/examples.html
  docs/examples/viewconfs/overlay-chromosome-grid-track.json
  docs/examples/viewconfs/overlay-track.json
  docs/view_config.rst
  test/OverlayTrackTests.js
  test/view-configs/overlay-chrom-grid.js
Labels: enhancement

#532 Flekschas/expose d3 libs to plugins
  CHANGELOG.md
  app/scripts/configs/available-for-plugins.js
  docs/index.rst
  docs/plugin_track.rst
  karma.conf.js
  test/PluginTrackTests.js
  test/utils/DummyTrack.js
  test/view-configs/dummy-track.js
Labels: documentation, enhancement

#475 Flekschas/add lint hook
  .huskyrc
  .lintstagedrc
  app/scripts/Chromosome2DLabels.js
  app/scripts/HiGlassComponent.js
  package.json
Labels: enhancement

#538 Fixes overlay tracks to allow for multiple extent values and 4-tuples.
  CHANGELOG.md
  app/scripts/OverlayTrack.js
  docs/examples/apis/svg.html
  docs/examples/viewconfs/overlay-track.json
  docs/examples/viewconfs/overlay-tracks.json
  docs/view_config.rst
  test/view-configs/overlay-annotations-1d-2d.js
Labels: enhancement
