Repository higlass/higlass, pull requests merged in 2019-03, with the labels that each got.

#462 Flekschas/add margin to axis
  CHANGELOG.md
  app/scripts/AxisPixi.js
  app/scripts/HorizontalTiled1DPixiTrack.js
  app/scripts/configs/options-info.js
  app/scripts/configs/tracks-info.js
  docs/examples/apis/axis-margin.html
  docs/examples/examples.html
  docs/examples/viewconfs/axis-margin.json
  docs/view_config.rst
  test/AxisTests.js
  test/view-configs/axis.js
Labels: enhancement

#557 Added doc about `APP_BASEPATH`
  docs/higlass_server.rst
Labels: documentation

#581 Fix #578
  CHANGELOG.md
  app/scripts/BarTrack.js
  docs/examples/examples.html
  docs/examples/viewconfs/bar-track.json
Labels: bug

#577 Flekschas/hot fix wheel blocking
  CHANGELOG.md
  app/scripts/HiGlassComponent.js
Labels: bug, critical

#576 Flekschas/fix value limit rendering issue with bar charts
  app/scripts/BarTrack.js
  app/scripts/TiledPixiTrack.js
Labels: bug, critical

#470 Flekschas/adjustable view spacing
  CHANGELOG.md
  app/scripts/HiGlassComponent.js
  app/scripts/HorizontalTiledPlot.js
  app/scripts/TiledPlot.js
  app/scripts/TrackRenderer.js
  app/scripts/configs/index.js
  docs/examples/others/adjust-view-spacing.html
  docs/javascript_api.rst
  package.json
  test/APITests.js
  test/view-configs/adjust-view-spacing.js
Labels: enhancement

#582 Flekschas/fix bar small offset svg rendering
  CHANGELOG.md
  app/scripts/BarTrack.js
  docs/examples/apis/svg.html
Labels: bug

#367 Flekschas/add label margin
  CHANGELOG.md
  app/scripts/PixiTrack.js
  app/scripts/configs/options-info.js
  app/scripts/configs/tracks-info.js
  docs/examples/examples.html
  docs/examples/viewconfs/label-margin.json
  docs/view_config.rst
  test/LabelTests.js
  test/view-configs/label-margin.js
Labels: enhancement, feature

#575 Flekschas/allow disabling view header and track menu separatebly
  CHANGELOG.md
  app/index.html
  app/scripts/HiGlassComponent.js
  app/scripts/TiledPlot.js
  app/scripts/TrackRenderer.js
  docs/javascript_api.rst
  docs/view_config.rst
Labels: enhancement

#580 Flekschas/bar track demarcation
  CHANGELOG.md
  app/scripts/BarTrack.js
  app/scripts/configs/options-info.js
  app/scripts/configs/tracks-info.js
  docs/examples/apis/svg.html
  docs/examples/examples.html
  docs/examples/viewconfs/bar-zero-line.json
  docs/track_types.rst
  test/BarTrackTests.js
  test/view-configs/bar.js
Labels: enhancement

#583 Convert to number before checking for NaN
  CHANGELOG.md
  app/scripts/TiledPixiTrack.js
Labels: bug, easy

#585 Flekschas/fix 584
  CHANGELOG.md
  app/scripts/TiledPlot.js
  docs/examples/apis/reset-viewport.html
  test/APITests.js
  test/view-configs/simple-heatmap.js
Labels: bug, easy

#565 Update README.md
  README.md
Labels: documentation
