Repository higlass/higlass, pull requests merged in 2019-08, with the labels that each got.

#758 Flekschas/update docs
  docs/_templates/layout.html
  docs/conf.py
  docs/higlass_theme/static/higlass.css
Labels: documentation

#748 Flekschas/fix tooltip value
  CHANGELOG.md
  app/scripts/utils/ndarray-assign.js
Labels: bug, critical

#714 Update labelled points documentation
  docs/jupyter.rst
Labels: documentation

#753 Add check for setting proper GitHub labels to the PR template. Minor changes to the wording.
  PULL_REQUEST_TEMPLATE.md
Labels: documentation

#761 Fix drag over coloring
  CHANGELOG.md
  app/scripts/DragListeningDiv.js
  app/scripts/api.js
Labels: bug

#752 Add import statement to docs
  docs/jupyter.rst
Labels: documentation

#742 Genbank data fetcher
  CHANGELOG.md
  COMMANDS
  app/schema.json
  app/scripts/DataFetcher.js
  app/scripts/HiGlassComponent.js
  app/scripts/HorizontalTiled1DPixiTrack.js
  app/scripts/TiledPixiTrack.js
  app/scripts/Track.js
  app/scripts/TrackRenderer.js
  app/scripts/data-fetchers/genbank-fetcher.js
  app/scripts/data-fetchers/get-data-fetcher.js
  app/scripts/hglib.js
  docs/examples/examples.html
  docs/examples/viewconfs/genbank-data-fetcher.json
  docs/view_config.rst
  karma.conf.js
  package-lock.json
  package.json
  test/GenbankFetcherTests.js
  webpack.config.amd.dev.js
  webpack.config.amd.js
Labels: feature
