Repository higlass/higlass, pull requests merged in 2019-10, with the labels that each got.

#790 Fix moving horizontal rules bug
  CHANGELOG.md
  app/scripts/HorizontalRule.js
  app/scripts/TrackRenderer.js
  app/scripts/VerticalRule.js
  test/RuleTests.js
Labels: bug

#793 Show Loading... when retrieving a tileset
  CHANGELOG.md
  app/scripts/data-fetchers/genbank-fetcher.js
Labels: bug

#572 Flekschas/scrollable container
  CHANGELOG.md
  app/scripts/HiGlassComponent.js
  app/scripts/TiledPlot.js
  app/scripts/TrackRenderer.js
  app/scripts/api.js
  docs/examples/examples.html
  docs/examples/others/scrollable-container-multiple-views.html
  docs/examples/others/scrollable-container.html
  docs/javascript_api.rst
  test/APITests.js
  test/utils/create-element-and-api.js
  test/view-configs-more/stacked-top-tracks.json
  test/view-configs.js
Labels: feature

#794 Flekschas/enhance value locks
  CHANGELOG.md
  app/schema.json
  app/scripts/HiGlassComponent.js
  schema_build_test.sh
Labels: enhancement

#795 Flekschas/fix scrollable multi views
  app/scripts/HiGlassComponent.js
  app/scripts/TiledPlot.js
  app/scripts/TrackRenderer.js
  docs/examples/others/scrollable-container-multiple-views.html
  test/APITests.js
  test/view-configs-more/stacked-top-views.json
  test/view-configs.js
Labels: enhancement
