Repository higlass/higlass, pull requests merged in 2019-05, with the labels that each got.

#650 Update pub-sub-es
  CHANGELOG.md
  package-lock.json
  package.json
Labels: bug, critical

#655 Updated the docs with information about assemblies
  docs/data_preparation.rst
Labels: documentation

#635 Added oakland trees map overlay example to docs
  CHANGELOG.md
  docs/img/oakland-trees-map.png
  docs/jupyter.rst
Labels: documentation

#659 Fix #656 Fix #657
  app/styles/Modal.module.scss
Labels: bug, critical

#660 Flekschas/fix svg export
  CHANGELOG.md
  app/scripts/HiGlassComponent.js
Labels: bug

#649 Flekschas/viewconf editor
  CHANGELOG.md
  app/scripts/Button.js
  app/scripts/ConfigViewMenu.js
  app/scripts/Dialog.js
  app/scripts/HiGlassComponent.js
  app/scripts/Modal.js
  app/scripts/ViewConfigEditor.js
  app/scripts/ViewHeader.js
  app/scripts/utils/index.js
  app/scripts/utils/timeout.js
  app/styles/Button.module.scss
  app/styles/Dialog.module.scss
  app/styles/HiGlass.scss
  app/styles/Modal.module.scss
  app/styles/ViewConfigEditor.module.scss
  app/styles/prism.css
  docs/view_config.rst
  package-lock.json
  package.json
  test/ViewConfigEditorTests.js
  test/view-configs/simple-heatmap-gene-annotations.js
Labels: feature
