Repository higlass/higlass, pull requests merged in 2019-04, with the labels that each got.

#606 Include a full working html example of JS api
  CHANGELOG.md
  COMMANDS
  docs/COMMANDS
  docs/javascript_api.rst
  package-lock.json
  package.json
Labels: documentation

#604 Deploy docs to s3//higlass/docs-*
  .travis.yml
  CHANGELOG.md
Labels: documentation

#602 Specify available track types in `showAvailableTrackPositions`
  CHANGELOG.md
  app/scripts/DragListeningDiv.js
  app/scripts/TiledPlot.js
  app/scripts/api.js
  app/scripts/configs/default-tracks-for-datatype.js
  docs/examples/others/test_drag.html
  test/APITests.js
Labels: enhancement

#598 Overlay track fix and use default height for new tracks
  CHANGELOG.md
  app/scripts/HiGlassComponent.js
  app/scripts/TiledPlot.js
  karma.conf.js
  test/OverlayTrackTests.js
Labels: bug

#617 Fix #612
  CHANGELOG.md
  app/scripts/GenomePositionSearchBox.js
  app/scripts/SearchField.js
  test/GenomePositionSearchBoxTest.js
  test/HiGlassComponentTest.js
Labels: bug
