Repository higlass/higlass, pull requests merged in 2019-07, with the labels that each got.

#709 Flekschas/auto zoom to extent
  CHANGELOG.md
  app/scripts/HiGlassComponent.js
  app/scripts/TiledPlot.js
  test/AddTrackTests.js
  test/view-configs-more/oneViewConfig.json
Labels: bug

#710 Pkerpedjiev/df points docs
  docs/img/geojson-jupyter.png
  docs/jupyter.rst
Labels: documentation

#712 Support boolean values too
  CHANGELOG.md
  app/scripts/HeatmapTiledPixiTrack.js
Labels: bug

#713 Flekschas/svg export fix namespace
  CHANGELOG.md
  app/scripts/HiGlassComponent.js
Labels: bug, critical

#716 Flekschas/micro fixes
  CHANGELOG.md
  app/scripts/ViewConfigEditor.js
  app/scripts/services/tile-proxy.js
Labels: bug, enhancement

#715 Add two examples for the NYC taxi dataset
  docs/examples/others/nyc-taxi-division.html
  docs/examples/others/nyc-taxi.html
Labels: documentation

#718 Flekschas/micro fixes
  CHANGELOG.md
  app/scripts/AddTrackDialog.js
  app/styles/AddTrackModal.css
  app/styles/Button.module.scss
  app/styles/Dialog.module.scss
  app/styles/Modal.module.scss
  app/styles/TilesetFinder.css
  app/styles/ViewConfigEditor.module.scss
  app/styles/sizes.scss
Labels: bug

#720 Flekschas/fix horizontal heatmap track rendering
  CHANGELOG.md
  app/scripts/HorizontalHeatmapTrack.js
Labels: bug

#721 Flekschas/expose pixi renderer
  CHANGELOG.md
  app/scripts/HiGlassComponent.js
  app/scripts/TiledPlot.js
  app/scripts/TrackRenderer.js
Labels: bug, critical, enhancement

#723 Flekschas/fix 1d heatmap
  CHANGELOG.md
  app/scripts/Horizontal1dHeatmapTrack.js
Labels: bug, critical

#724 Fix #722
  CHANGELOG.md
  app/scripts/PixiTrack.js
  app/scripts/configs/options-info.js
  app/scripts/configs/tracks-info.js
Labels: enhancement

#728 Dynamically update dark theme when the options change
  CHANGELOG.md
  app/scripts/HiGlassComponent.js
Labels: bug, enhancement

#727 Only compare tracks that are suppose to receive a tileset info
  CHANGELOG.md
  app/scripts/TiledPlot.js
Labels: bug

#734 Remove the hold ALT feature as it's confusion
  CHANGELOG.md
  app/scripts/ViewConfigEditor.js
  test/ViewConfigEditorTests.js
Labels: enhancement

#738 Flekschas/copy tile data before mutating
  CHANGELOG.md
  app/scripts/DataFetcher.js
  app/scripts/TiledPixiTrack.js
  app/scripts/services/tile-proxy.js
  test/HeatmapTests.js
Labels: bug

#739 Flekschas/do not leak dark mode
  CHANGELOG.md
  app/scripts/AddTrackPositionMenu.js
  app/scripts/AxisPixi.js
  app/scripts/ConfigTrackMenu.js
  app/scripts/ConfigViewMenu.js
  app/scripts/ContextMenuContainer.js
  app/scripts/DraggableDiv.js
  app/scripts/GenomePositionSearchBox.js
  app/scripts/HiGlassComponent.js
  app/scripts/HorizontalChromosomeLabels.js
  app/scripts/HorizontalGeneAnnotationsTrack.js
  app/scripts/NestedContextMenu.js
  app/scripts/SeriesListMenu.js
  app/scripts/SeriesListSubmenuMixin.js
  app/scripts/TiledPlot.js
  app/scripts/Track.js
  app/scripts/TrackControl.js
  app/scripts/TrackRenderer.js
  app/scripts/ViewContextMenu.js
  app/scripts/ViewHeader.js
  app/scripts/api.js
  app/scripts/configs/index.js
  app/scripts/configs/themes.js
  app/scripts/configs/tracks-info.js
  app/scripts/hocs/with-theme.js
  app/scripts/services/index.js
  app/scripts/services/is-dark-theme.js
  docs/examples/others/dark-theme.html
  docs/examples/others/nyc-taxi.html
  test/HiGlassComponentTest.js
Labels: bug, enhancement

#740 Flekschas/add scipy talk to docs
  README.md
  docs/conf.py
  docs/environment.yml
  docs/examples/others/minimal-working-example.html
  docs/img/higlass-architecture.jpg
  docs/index.rst
  docs/jupyter.rst
Labels: documentation

#744 Flekschas/add contributing md
  CONTRIBUTING.md
  package.json
Labels: documentation

#745 Flekschas/fix drag handle styling
  .travis.yml
  CHANGELOG.md
  app/scripts/DraggableDiv.js
  app/styles/DraggableDiv.module.scss
Labels: bug, enhancement

#746 Flekschas/fix tooltip position when page was scrolled
  CHANGELOG.md
  app/scripts/HiGlassComponent.js
Labels: bug
