Repository higlass/higlass, pull requests merged in 2019-02, with the labels that each got.

#554 Flekschas/expose version
  CHANGELOG.md
  app/scripts/hglib.js
  docs/javascript_api.rst
Labels: enhancement

#570 Flekschas/fix big finger mode and other visual glitches
  CHANGELOG.md
  app/styles/HiGlass.scss
  app/styles/ViewHeader.module.scss
Labels: bug

#556 Mention Python 3 requirement
  docs/tutorial.rst
Labels: documentation
