Repository higlass/higlass, pull requests merged in 2019-09, with the labels that each got.

#762 Value scale zooming
  CHANGELOG.md
  app/scripts/BarTrack.js
  app/scripts/LeftTrackModifier.js
  app/scripts/Track.js
  app/scripts/TrackRenderer.js
  karma.conf.js
  test/ZoomTests.js
  test/view-configs/two-bars-and-a-heatmap.json
Labels: enhancement

#767 Common trackUtils function
  CHANGELOG.md
  app/scripts/utils/index.js
  app/scripts/utils/track-utils.js
Labels: enhancement

#768 Flekschas/enable brushing on bar point 1d heatmap tracks
  CHANGELOG.md
  app/scripts/configs/is-track-range-selectable.js
Labels: enhancement

#770 Limit icon size in plot type chooser
  CHANGELOG.md
  app/scripts/PlotTypeChooser.js
  app/styles/PlotTypeChooser.css
Labels: bug

#769 Add api call to show track chooser
  CHANGELOG.md
  app/scripts/TiledPlot.js
  app/scripts/api.js
  docs/examples/others/test_drag.html
Labels: enhancement

#771 Check whether genbank files are gzipped and better handle errors
  CHANGELOG.md
  app/scripts/PixiTrack.js
  app/scripts/data-fetchers/genbank-fetcher.js
  package-lock.json
Labels: bug

#776 Allow viewconf to override min dims with `minHeight` or `minWidth` props (2)
  CHANGELOG.md
  app/schema.json
  app/scripts/HiGlassComponent.js
  app/scripts/configs/tracks-info.js
  app/scripts/utils/fill-in-min-widths.js
  app/scripts/utils/test-helpers.js
  docs/view_config.rst
  karma.conf.js
  package.json
  test/APITests.js
  test/HiGlassComponentTest.js
  test/HorizontalMultivecTests.js
  test/view-configs-more/horizontalMultivecWithSmallerDimensions.json
  test/view-configs-more/paperFigure1.json
  test/view-configs-more/simpleCenterViewConfig.json
  test/view-configs-more/valueIntervalTrackViewConf.json
Labels: enhancement

#774 Overlay track bug fixes
  CHANGELOG.md
  app/scripts/HorizontalGeneAnnotationsTrack.js
  app/scripts/OverlayTrack.js
  app/scripts/TiledPlot.js
  app/scripts/TrackRenderer.js
Labels: bug

#777 Flekschas/overlay min width height
  CHANGELOG.md
  app/scripts/OverlayTrack.js
  app/scripts/utils/fill-in-min-widths.js
  docs/examples/viewconfs/overlay-track.json
Labels: enhancement

#781 Rename unsafe react lifecycle methods and update packages
  CHANGELOG.md
  app/scripts/Autocomplete.js
  app/scripts/ContextMenuContainer.js
  app/scripts/DraggableDiv.js
  app/scripts/HiGlassComponent.js
  app/scripts/ListWrapper.js
  app/scripts/PlotTypeChooser.js
  app/scripts/TiledPlot.js
  app/scripts/TrackRenderer.js
  package-lock.json
  package.json
Labels: technical debt
