Repository higlass/higlass, pull requests merged in 2020-01, with the labels that each got.

#817 alexander-veit/default plot types when adding tracks
  CHANGELOG.md
  app/scripts/AddTrackDialog.js
  app/scripts/HiGlassComponent.js
  app/scripts/PlotTypeChooser.js
  app/scripts/TiledPlot.js
  app/scripts/configs/default-tracks-for-datatype.js
  app/scripts/utils/get-default-track-for-datatype.js
  app/scripts/utils/index.js
  app/styles/PlotTypeChooser.css
  docs/track_types.rst
  test/AddTrackTests.js
Labels: bug

#818 Segment style for bedlike tracks
  CHANGELOG.md
  app/scripts/BedLikeTrack.js
  app/scripts/configs/options-info.js
  app/scripts/configs/tracks-info.js
  docs/img/box-style.png
  docs/img/segment-style.png
  docs/track_types.rst
  test/BedLikeTests.js
Labels: enhancement

#820 Flelschas/small options fix
  app/scripts/HeatmapTiledPixiTrack.js
  app/scripts/PixiTrack.js
Labels: enhancement

#807 Added the option to flip and mirror 2d annotations
  CHANGELOG.md
  app/scripts/ArrowheadDomainsTrack.js
  app/scripts/configs/options-info.js
  app/scripts/configs/tracks-info.js
  docs/track_types.rst
  test/2DRectangleDomainsTests.js
  test/view-configs/loop-annotations.js
Labels: enhancement

#816 Added valueScaleMin / valueScaleMax options ...
  docs/track_types.rst
Labels: documentation

#821 Add troubleshooting section to docs
  docs/index.rst
  docs/troubleshooting.rst
Labels: documentation

#840 Ticks that mark the bounds of the view
  CHANGELOG.md
  app/scripts/HorizontalChromosomeLabels.js
  app/scripts/configs/options-info.js
  app/scripts/configs/tracks-info.js
  app/scripts/utils/pixi-text-to-svg.js
  docs/developer.rst
  docs/track_types.rst
  karma.conf.js
  test/ChromosomeLabelsTests.js
Labels: enhancement

#843 Fixed adding position to track defs
  CHANGELOG.md
  app/scripts/TiledPlot.js
  package-lock.json
  package.json
  test/ChromosomeLabelsTests.js
Labels: bug

#844 Run prettier
  app/scripts/configs/datatype-to-track-type.js
  app/scripts/configs/options-info.js
  app/scripts/configs/tracks-info.js
  app/scripts/data-fetchers/genbank-fetcher.js
  app/scripts/hocs/with-modal.js
  app/scripts/hocs/with-pub-sub.js
  app/scripts/hocs/with-theme.js
  app/scripts/services/dom-event.js
  app/scripts/services/element-resize-listener.js
  app/scripts/services/tile-proxy.js
  app/scripts/utils/abs-to-chr.js
  app/scripts/utils/color-domain-to-rgba-array.js
  app/scripts/utils/dict-items.js
  app/scripts/utils/fill-in-min-widths.js
  app/scripts/utils/get-default-track-for-datatype.js
  app/scripts/utils/get-higlass-components.js
  app/scripts/utils/get-track-obj-by-id.js
  app/scripts/utils/gradient.js
  app/scripts/utils/interval-tree.js
  app/scripts/utils/is-within.js
  app/scripts/utils/ndarray-to-list.js
  app/scripts/utils/numericify-version.js
  app/scripts/utils/show-mouse-position.js
  app/scripts/utils/test-helpers.js
  app/scripts/utils/total-track-pixel-height.js
  app/scripts/utils/track-utils.js
  app/scripts/utils/value-to-color.js
  app/scripts/utils/visit-positioned-tracks.js
  app/scripts/utils/visit-tracks.js
Labels: technical debt
