Repository higlass/higlass, pull requests merged in 2020-08, with the labels that each got.

#959 Allow tracks to modify their width and height
  CHANGELOG.md
  app/scripts/HiGlassComponent.js
  app/scripts/TrackRenderer.js
  test/HiGlassComponentTest.js
Labels: enhancement

#963 Flekschas/simplify plugin track registry
  CHANGELOG.md
  app/scripts/HiGlassComponent.js
  karma.conf.js
Labels: enhancement

#972 Fix plugin track registration
  CHANGELOG.md
  app/scripts/HiGlassComponent.js
Labels: bug, critical

#973 Autodoc the off function
  docs/javascript_api.rst
Labels: documentation

#976 Show all available track types
  CHANGELOG.md
  app/scripts/SeriesListMenu.js
Labels: bug
