Repository higlass/higlass, pull requests merged in 2020-06, with the labels that each got.

#927 Make sure setViewConfig promise resolves
  CHANGELOG.md
  app/scripts/api.js
  test/APITests.js
Labels: bug

#928 Remove random td tag
  CHANGELOG.md
  app/styles/TiledPlot.module.scss
Labels: bug

#936 Update the genbank fetcher to read raw data
  CHANGELOG.md
  app/scripts/data-fetchers/genbank-fetcher.js
  docs/view_config.rst
  test/GenbankFetcherTests.js
Labels: enhancement

#940 Fix overlay example. Close #939
  docs/view_config.rst
Labels: documentation

#930 Consolidated horizontal and vertical tracks
  .gitattributes
  .prettierrc
  .travis.yml
  CHANGELOG.md
  app/schema.json
  app/scripts/HiGlassComponent.js
  app/scripts/Tiled1DPixiTrack.js
  app/scripts/TilesetFinder.js
  app/scripts/TrackRenderer.js
  app/scripts/configs/datatype-to-track-type.js
  app/scripts/configs/default-tracks-for-datatype.js
  app/scripts/configs/tracks-info-by-type.js
  app/scripts/configs/tracks-info.js
  app/scripts/icons.js
  docs/track_types.rst
  karma.conf.js
  test/AddTrackTests.js
  test/GeneAnnotationsTrackTests.js
  test/HiGlassComponentTest.js
  test/TrackLabelsTest.js
  test/ZoomTests.js
  travis_build_test.sh
Labels: enhancement

#942 Colored rules
  CHANGELOG.md
  app/scripts/CrossRule.js
  app/scripts/HorizontalRule.js
  app/scripts/SeriesListItems.js
  app/scripts/VerticalRule.js
  app/scripts/configs/tracks-info.js
  app/scripts/utils/index.js
  app/scripts/utils/test-helpers.js
  test/RuleTests.js
Labels: enhancement
